### ISSUE TITLE
question about find out design smell

### ISSUE THREAD

**Issue by xiaozhiliaoo** [tushartushar/smells#3]
I recently read your excellent book **Refactoring for Software Design Smells**.  You list a lot of JDK source code smell. for example, 
 hub class java.util.Component. I'm curious how did you find out？I appreciate you can reply me.

**Comment by tushartushar** [comment]
At the time of writing the book, we used available tools such as Structure101 to analyze JDK.

**Comment by xiaozhiliaoo** [comment]
> At the time of writing the book, we used available tools such as Structure101 to analyze JDK.

Thanks a lot.
